# File: /quicklynks/docker-compose.yml
version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: quicklynks-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      # Expose port 5432 to the host for local debugging if needed
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: quicklynks-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      # Mount source code for live reloading with Air
      - ./backend:/app
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      db:
        condition: service_healthy
    command: ["air", "-c", ".air.toml"]

  frontend:
    container_name: quicklynks-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      # Mount source code for SvelteKit's HMR
      - ./frontend:/app
      - /app/node_modules # Anonymous volume to prevent host node_modules from overwriting container's
    environment:
      - PUBLIC_API_BASE_URL=${PUBLIC_API_BASE_URL}
      - VITE_API_BASE_URL=${PUBLIC_API_BASE_URL} # Vite needs this format
    depends_on:
      - backend

volumes:
  postgres_data:
