# File: /quicklynks/backend/.air.toml
# Config file for Air live-reloader
root = "."
tmp_dir = "tmp"

[build]
# Command to build the Go binary
cmd = "go build -o ./tmp/main ./cmd/api"
# The binary to run
bin = "tmp/main"
# Files to watch for changes
include_ext = ["go", "tpl", "tmpl", "html"]
# Directories to exclude from watching
exclude_dir = ["tmp", "vendor", "test", "docs"]
# Log name
log = "air_errors.log"
# Delay between build and run
delay = 1000 # ms

[log]
# Show log time
time = true

[color]
# Customize colors
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true